<a href="https://colab.research.google.com/github/zeynepsenatatli/DataAnalysisMethods_with_Python/blob/main/Lab6_Multi_Index_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
# load data
df = pd.read_csv('WordsByCharacter.csv')
df

,Film,Chapter,Character,Race,Words
0,The Fellowship Of The Ring,01: Prologue,Bilbo,Hobbit,4
1,The Fellowship Of The Ring,01: Prologue,Elrond,Elf,5
2,The Fellowship Of The Ring,01: Prologue,Galadriel,Elf,460
3,The Fellowship Of The Ring,01: Prologue,Gollum,Gollum,20
4,The Fellowship Of The Ring,02: Concerning Hobbits,Bilbo,Hobbit,214
...,...,...,...,...,...
726,The Return Of The King,76: The Grey Havens,Elrond,Elf,6
727,The Return Of The King,76: The Grey Havens,Frodo,Hobbit,132
728,The Return Of The King,76: The Grey Havens,Galadriel,Elf,17
729,The Return Of The King,76: The Grey Havens,Gandalf,Ainur,42
730,The Return Of The King,76: The Grey Havens,Sam,Hobbit,14

In [ ]:
df.index.names

FrozenList([None])

In [ ]:
multi = df.set_index(['Film', 'Chapter', 'Race', 'Character'])
multi

                                                                    Words
Film                       Chapter                Race   Character
The Fellowship Of The Ring 01: Prologue           Hobbit Bilbo          4
                                                  Elf    Elrond         5
                                                         Galadriel    460
                                                  Gollum Gollum        20
                           02: Concerning Hobbits Hobbit Bilbo        214
...                                                                   ...
The Return Of The King     76: The Grey Havens    Elf    Elrond         6
                                                  Hobbit Frodo        132
                                                  Elf    Galadriel     17
                                                  Ainur  Gandalf       42
                                                  Hobbit Sam           14

[731 rows x 1 columns]

In [ ]:
multi.index.names

FrozenList(['Film', 'Chapter', 'Race', 'Character'])

In [ ]:
multi.index.values

In [ ]:
multi = df.set_index(["Film", "Chapter", "Race", "Character"]).sort_index()
multi

                                                                                               Words
Film                       Chapter                                           Race   Character
The Fellowship Of The Ring 01: Prologue                                      Elf    Elrond         5
                                                                                    Galadriel    460
                                                                             Gollum Gollum        20
                                                                             Hobbit Bilbo          4
                           02: Concerning Hobbits                            Hobbit Bilbo        214
...                                                                                              ...
The Two Towers             65: The Battle For Middle Earth Is About To Begin Hobbit Sam           69
                           66: Gollum's Plan                                 Gollum Gollum        75
                                                                                    Smeagol       53
                                                                             Hobbit Frodo         11
                                                                                    Sam           12

[731 rows x 1 columns]

In [ ]:
multi.reset_index()

,Film,Chapter,Race,Character,Words
0,The Fellowship Of The Ring,01: Prologue,Elf,Elrond,5
1,The Fellowship Of The Ring,01: Prologue,Elf,Galadriel,460
2,The Fellowship Of The Ring,01: Prologue,Gollum,Gollum,20
3,The Fellowship Of The Ring,01: Prologue,Hobbit,Bilbo,4
4,The Fellowship Of The Ring,02: Concerning Hobbits,Hobbit,Bilbo,214
...,...,...,...,...,...
726,The Two Towers,65: The Battle For Middle Earth Is About To Begin,Hobbit,Sam,69
727,The Two Towers,66: Gollum's Plan,Gollum,Gollum,75
728,The Two Towers,66: Gollum's Plan,Gollum,Smeagol,53
729,The Two Towers,66: Gollum's Plan,Hobbit,Frodo,11
730,The Two Towers,66: Gollum's Plan,Hobbit,Sam,12

In [ ]:
multi.loc[('The Fellowship Of The Ring', '01: Prologue'), :]

                  Words
Race   Character
Elf    Elrond         5
       Galadriel    460
Gollum Gollum        20
Hobbit Bilbo          4

In [ ]:
multi.loc[("The Fellowship Of The Ring",slice(None),"Elf"), :].head(3)

                                                                  Words
Film                       Chapter                Race Character
The Fellowship Of The Ring 01: Prologue           Elf  Elrond         5
                                                       Galadriel    460
                           21: Flight To The Ford Elf  Arwen        131

In [ ]:
multi.loc[('The Two Towers',slice(None),slice(None),['Gandalf','Saruman']), :]

                                                                                  Words
Film           Chapter                                           Race  Character
The Two Towers 01: The Foundations Of Stone                      Ainur Gandalf       39
               06: The Burning of the Westfold                   Ainur Saruman      187
               15: The White Rider                               Ainur Gandalf      298
               17: The Heir Of NÃºmenor                           Ainur Gandalf      226
               20: The King Of The Golden Hall                   Ainur Gandalf      151
               22: SimbelmynÃ« on the Burial Mounds               Ainur Gandalf       28
               23: The King's Decision                           Ainur Gandalf      165
               25: The Ring Of Barahir                           Ainur Saruman       68
               27: Exodus From Edoras                            Ainur Saruman        4
               36: Isengard Unleashed                            Ainur Saruman       50
               58: Forth Eorlingas                               Ainur Gandalf       21
               65: The Battle For Middle Earth Is About To Begin Ainur Gandalf       36

In [ ]:
multi.xs('Isildur', level='Character').sum()

Words    1
dtype: int64

In [ ]:
pivoted = df.pivot_table(index = ['Race','Character'],
                         columns = 'Film',
                         aggfunc = 'sum',
                         margins = True, # total column
                         margins_name = 'All Films',
                         fill_value = 0).sort_index()
order = [('Words', 'The Fellowship Of The Ring'),
         ('Words', 'The Two Towers'),
         ('Words', 'The Return Of The King'), 
         ('Words', 'All Films')]
pivoted = pivoted.sort_values(by=('Words', 'All Films'), ascending=False)
pivoted = pivoted.reindex(order, axis=1)
pivoted

                                                Words                 \
Film                       The Fellowship Of The Ring The Two Towers
Race      Character
All Films                                       11225          11169
Ainur     Gandalf                                2360            964
Hobbit    Sam                                     557           1044
Men       Aragorn                                 920            822
Hobbit    Frodo                                   967            664
...                                               ...            ...
          Mrs. Bracegirdle                          2              0
Orc       Mauhur                                    0              2
Men       Eothain                                   0              2
Hobbit    Proudfoot                                 1              0
Men       Isildur                                   1              0


Film                       The Return Of The King All Films
Race      Character
All Films                                    9575     31969
Ainur     Gandalf                            1504      4828
Hobbit    Sam                                 924      2525
Men       Aragorn                             580      2322
Hobbit    Frodo                               650      2281
...                                           ...       ...
          Mrs. Bracegirdle                      0         2
Orc       Mauhur                                0         2
Men       Eothain                               0         2
Hobbit    Proudfoot                             0         1
Men       Isildur                               0         1

[75 rows x 4 columns]

In [ ]:
pivoted.loc['Hobbit']

                                               Words                 \
Film                      The Fellowship Of The Ring The Two Towers
Character
Sam                                              557           1044
Frodo                                            967            664
Bilbo                                           1310              0
Pippin                                           274            359
Merry                                            323            396
Hobbits                                           88              0
Ted                                               55              0
Gaffer                                            21              0
Farmer Maggot                                     21              0
Sandyman                                          17              0
Deagol                                             0              0
Hobbit Kids                                       10              0
Lobelia Sackville-Baggins                          9              0
Rosie                                              3              0
Mrs. Bracegirdle                                   2              0
Proudfoot                                          1              0


Film                      The Return Of The King All Films
Character
Sam                                          924      2525
Frodo                                        650      2281
Bilbo                                         56      1366
Pippin                                       628      1261
Merry                                        398      1117
Hobbits                                        4        92
Ted                                            0        55
Gaffer                                         0        21
Farmer Maggot                                  0        21
Sandyman                                       0        17
Deagol                                        13        13
Hobbit Kids                                    0        10
Lobelia Sackville-Baggins                      0         9
Rosie                                          2         5
Mrs. Bracegirdle                               0         2
Proudfoot                                      0         1